apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "d90ka59mcH9a34P" # Note this is sample password used for demo purpose and to aware you should use strong passwords like this
            - name: MYSQL_DATABASE
              value: "flaskdb"
            - name: MYSQL_USER
              value: "mubin"
            - name: MYSQL_PASSWORD
              value: "d90ka59mcH9a343" # Note this is sample password used for demo purpose and to aware you should use strong passwords like this
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysqldata
              mountPath: /var/lib/mysql         # this is your container path from where your data will be stored
      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: mysql-pvc    # PVC claim name